export enum PO_DETERMINATION_LABEL {
  soleSource = 'Sole Source',
  emergencyProcurement = 'Emergency procurement where only one bid was received',
  requestForQuotationsInvitationForBidOnlyOne = 'Request for Quotations or Invitations for Bid',
  requestForQuotationsInvitationForBidLowest = 'Request for Quotations where lowest is not selected',
  requestForProposals = 'Solicitation of competitive proposals where only one proposal is received',
  priceAdjustment = 'Price adjustment to Contract No.',
  exemptProcurement = 'Services contract not admitting of competition',
  professionalSvcProcurement = 'Professional services',
  extension = 'Extension of an existing contract',
  other = 'Other',

  reason1 = '1.',
  reason2 = '2.',
  reason3 = '3.',
  reason4 = '4.',
  reason5 = '5.',
  reason6 = '6.',
  reason7 = '7.',
}
