export enum VENDOR_KEY {
  CODE = 'code',
  LINE1 = 'line1',
  LINE2 = 'line2',
  // TODO: Tuyen Tran will replace name,name2 if don't need
  NAME = 'name',
  NAME2 = 'name2',
  TYPE = 'type',
  PAYMENT_TYPE = 'paymentType',
  PURGED = 'purged',
  ADDRESS1 = 'address1',
  ADDRESS2 = 'address2',
  ADDRESS3 = 'address3',
  CREATED = 'created',
  UPDATED = 'updated',
  W9 = 'w9',
  W9_TOOLTIP = 'w9Tooltip',
  ZIP = 'zip',
  ZIP_4 = 'zip4',
  RCUH_EMP_NUMBER = 'rcuhEmpNumber',
  UH_EMP_NUMBER = 'uhEmpNumber',
  SSN = 'ssn',
  VENDOR_REGISTRATION_EXISTS = 'vendorRegistrationExists',
}
