export enum VENDOR_REGISTRATION_PARAMS {
  CALLING_FROM = 'callingFrom',
  DOCUMENT_ID = 'documentId',
  VENDOR_REGISTRATION_ID = 'vendorRegistrationId',
}

export enum VENDOR_REGISTRATION_NAVIGATE_FROM {
  PO = 'PO',
  NON_PO = 'NON_PO',
  TRAVEL = 'TRAVEL',
  VIEW_VENDOR_REGISTRATION = 'VIEW_VENDOR_REGISTRATION',
}
