export enum VENDOR_REGISTRATION_PARAMS {
  CALLING_FROM = 'callingFrom',
  DOCUMENT_ID = 'documentId',
  VENDOR_REGISTRATION_ID = 'vendorRegistrationId',
}

export enum VENDOR_REGISTRATION_NAVIGATE_FROM {
  PO = 'PO',
  AUTHORIZATION_PAYMENT = 'AUTHORIZATION_PAYMENT',
  NON_EMPLOYEE_TRAVEL_PAYMENT = 'NON_EMPLOYEE_TRAVEL_PAYMENT',
  PETTY_CASH_PAYMENT = 'PETTY_CASH_PAYMENT',
  PERSONAL_AUTO_PAYMENT = 'PERSONAL_AUTO_PAYMENT',
  TRAVEL = 'TRAVEL',
  VIEW_VENDOR_REGISTRATION = 'VIEW_VENDOR_REGISTRATION',
}
