export enum PO_DETAIL_STATUS {
  PI_PENDING_SUBMITTAL = 'PI_PENDING_SUBMITTAL',
  FA_PENDING_APPROVAL = 'FA_PENDING_APPROVAL',
  PI_ADDITIONAL_INFO_REQUESTED = 'PI_ADDITIONAL_INFO_REQUESTED',
  PI_DISAPPROVED = 'PI_DISAPPROVED',
  FA_ADDITIONAL_INFO_REQUESTED_RCUH = 'FA_ADDITIONAL_INFO_REQUESTED_RCUH',
  RCUH_PENDING_RCUH_APPROVAL = 'RCUH_PENDING_RCUH_APPROVAL',
  FINAL = 'FINAL',
}

export enum PO_DOCUMENT_TYPE {
  PURCHASE_ORDER = 'purchaseOrder',
  PO_CHANGE = 'poChange',
  PO_PAYMENT = 'poPayment',
}
